# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EVHS Hacking Club
email: evhacking@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the hacking club at Evergreen Valley High School, est. 2018. © EVHS Hacking Club, 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evl33t.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: evl33t
github_username:  evl33t

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Google analytics
google_analytics: UA-115077436-1

# Comments
# hypercomments_id: 102209
disqus:
    shortname: evl33t

# Show post excerpts
#excerpt_separator: <!--more-->
#show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Prose config
prose:
  siteurl: "https://evl33t.github.io"
  media: "media"
  relativeLinks: 'https://evl33t.github.io/links.jsonp'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Default"
              value: "default"
